<%@ page language="java" contentType="text/html; charset=UTF-8" pageEncoding="UTF-8"%>
<!DOCTYPE html>
<html>
<head>
    <title>Select Seats</title>
    <link href="../css/seat-selection.css" rel="stylesheet"/>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet">
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css" rel="stylesheet">
    <style>
        .seat.occupied {
            background-color: #ff4444;  /* Red color for occupied seats */
            cursor: not-allowed;
            pointer-events: none;
        }
        
        .seat.available {
            background-color: #444451;  /* Dark gray for available seats */
        }
        
        .seat.selected {
            background-color: #6feaf6;  /* Light blue for selected seats */
        }
        
        .seat-legend .occupied {
            background-color: #ff4444;
        }
    </style>
</head>
<body class="bg-dark text-white">
    <div class="container mt-5">
        <h2>Select Your Seats</h2>

        <div class="booking-info mt-3">
            <div class="booking-info-container">
                <div class="info-item">
                    <i class="fas fa-film"></i>
                    <span>Movie: ${sessionScope.selectedMovie}</span>
                </div>
                <div class="info-item">
                    <i class="fas fa-clock"></i>
                    <span>Show Time: ${sessionScope.selectedShowTime}</span>
                </div>
                <div class="info-item">
                    <i class="fas fa-calendar"></i>
                    <span>Date: ${sessionScope.selectedDate}</span>
                </div>
            </div>
        </div>

        <input type="hidden" id="movieId" value="${sessionScope.movieId}">
        <input type="hidden" id="showTime" value="${sessionScope.selectedShowTime}">
        <input type="hidden" id="bookingDate" value="${sessionScope.selectedDate}">
        
        <div class="screen-container">
            <div class="screen">Screen</div>
        </div>
        
        <div class="seat-map" id="seatMap">
            <!-- Seats will be generated by JavaScript -->
        </div>
        
        <div class="mt-4">
            <div class="seat-legend">
                <div class="seat available"></div> Available
                <div class="seat selected"></div> Selected
                <div class="seat occupied"></div> Occupied
            </div>
            
            <div class="booking-summary mt-4">
                <h4>Booking Summary</h4>
                <p>Selected Seats: <span id="selectedSeatsText">None</span></p>
                <p>Total Amount: <span id="totalAmount">0.00</span> LKR</p>
                <button id="proceedToPayment" class="btn btn-primary">Proceed to Payment</button>
            </div>
        </div>
    </div>
    <script>
        const SEAT_PRICE = parseFloat("${ticketPrice}");
        const TICKET_COUNT = parseInt("${sessionScope.ticketCount}");
    </script>
    <script src="../js/seat-selection.js"></script>
</body>
</html>
